// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dal-go/dalgo/dal (interfaces: Database,TransactionCoordinator,ReadTransactionCoordinator,ReadwriteTransactionCoordinator,Transaction,ReadTransaction,ReadwriteTransaction,ReadSession,WriteSession,ReadwriteSession)

// Package mocks4dal is a generated GoMock package.
package mocks4dal

import (
	context "context"
	reflect "reflect"

	dal "github.com/dal-go/dalgo/dal"
	gomock "github.com/golang/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockDatabase) Client() dal.ClientInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(dal.ClientInfo)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockDatabaseMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockDatabase)(nil).Client))
}

// Get mocks base method.
func (m *MockDatabase) Get(arg0 context.Context, arg1 dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockDatabaseMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDatabase)(nil).Get), arg0, arg1)
}

// GetMulti mocks base method.
func (m *MockDatabase) GetMulti(arg0 context.Context, arg1 []dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockDatabaseMockRecorder) GetMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockDatabase)(nil).GetMulti), arg0, arg1)
}

// ID mocks base method.
func (m *MockDatabase) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockDatabaseMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockDatabase)(nil).ID))
}

// QueryAllRecords mocks base method.
func (m *MockDatabase) QueryAllRecords(arg0 context.Context, arg1 dal.Query) ([]dal.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAllRecords", arg0, arg1)
	ret0, _ := ret[0].([]dal.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryAllRecords indicates an expected call of QueryAllRecords.
func (mr *MockDatabaseMockRecorder) QueryAllRecords(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAllRecords", reflect.TypeOf((*MockDatabase)(nil).QueryAllRecords), arg0, arg1)
}

// QueryReader mocks base method.
func (m *MockDatabase) QueryReader(arg0 context.Context, arg1 dal.Query) (dal.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryReader", arg0, arg1)
	ret0, _ := ret[0].(dal.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryReader indicates an expected call of QueryReader.
func (mr *MockDatabaseMockRecorder) QueryReader(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryReader", reflect.TypeOf((*MockDatabase)(nil).QueryReader), arg0, arg1)
}

// RunReadonlyTransaction mocks base method.
func (m *MockDatabase) RunReadonlyTransaction(arg0 context.Context, arg1 func(context.Context, dal.ReadTransaction) error, arg2 ...dal.TransactionOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunReadonlyTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunReadonlyTransaction indicates an expected call of RunReadonlyTransaction.
func (mr *MockDatabaseMockRecorder) RunReadonlyTransaction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReadonlyTransaction", reflect.TypeOf((*MockDatabase)(nil).RunReadonlyTransaction), varargs...)
}

// RunReadwriteTransaction mocks base method.
func (m *MockDatabase) RunReadwriteTransaction(arg0 context.Context, arg1 func(context.Context, dal.ReadwriteTransaction) error, arg2 ...dal.TransactionOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunReadwriteTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunReadwriteTransaction indicates an expected call of RunReadwriteTransaction.
func (mr *MockDatabaseMockRecorder) RunReadwriteTransaction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReadwriteTransaction", reflect.TypeOf((*MockDatabase)(nil).RunReadwriteTransaction), varargs...)
}

// MockTransactionCoordinator is a mock of TransactionCoordinator interface.
type MockTransactionCoordinator struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionCoordinatorMockRecorder
}

// MockTransactionCoordinatorMockRecorder is the mock recorder for MockTransactionCoordinator.
type MockTransactionCoordinatorMockRecorder struct {
	mock *MockTransactionCoordinator
}

// NewMockTransactionCoordinator creates a new mock instance.
func NewMockTransactionCoordinator(ctrl *gomock.Controller) *MockTransactionCoordinator {
	mock := &MockTransactionCoordinator{ctrl: ctrl}
	mock.recorder = &MockTransactionCoordinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionCoordinator) EXPECT() *MockTransactionCoordinatorMockRecorder {
	return m.recorder
}

// RunReadonlyTransaction mocks base method.
func (m *MockTransactionCoordinator) RunReadonlyTransaction(arg0 context.Context, arg1 func(context.Context, dal.ReadTransaction) error, arg2 ...dal.TransactionOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunReadonlyTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunReadonlyTransaction indicates an expected call of RunReadonlyTransaction.
func (mr *MockTransactionCoordinatorMockRecorder) RunReadonlyTransaction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReadonlyTransaction", reflect.TypeOf((*MockTransactionCoordinator)(nil).RunReadonlyTransaction), varargs...)
}

// RunReadwriteTransaction mocks base method.
func (m *MockTransactionCoordinator) RunReadwriteTransaction(arg0 context.Context, arg1 func(context.Context, dal.ReadwriteTransaction) error, arg2 ...dal.TransactionOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunReadwriteTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunReadwriteTransaction indicates an expected call of RunReadwriteTransaction.
func (mr *MockTransactionCoordinatorMockRecorder) RunReadwriteTransaction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReadwriteTransaction", reflect.TypeOf((*MockTransactionCoordinator)(nil).RunReadwriteTransaction), varargs...)
}

// MockReadTransactionCoordinator is a mock of ReadTransactionCoordinator interface.
type MockReadTransactionCoordinator struct {
	ctrl     *gomock.Controller
	recorder *MockReadTransactionCoordinatorMockRecorder
}

// MockReadTransactionCoordinatorMockRecorder is the mock recorder for MockReadTransactionCoordinator.
type MockReadTransactionCoordinatorMockRecorder struct {
	mock *MockReadTransactionCoordinator
}

// NewMockReadTransactionCoordinator creates a new mock instance.
func NewMockReadTransactionCoordinator(ctrl *gomock.Controller) *MockReadTransactionCoordinator {
	mock := &MockReadTransactionCoordinator{ctrl: ctrl}
	mock.recorder = &MockReadTransactionCoordinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadTransactionCoordinator) EXPECT() *MockReadTransactionCoordinatorMockRecorder {
	return m.recorder
}

// RunReadonlyTransaction mocks base method.
func (m *MockReadTransactionCoordinator) RunReadonlyTransaction(arg0 context.Context, arg1 func(context.Context, dal.ReadTransaction) error, arg2 ...dal.TransactionOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunReadonlyTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunReadonlyTransaction indicates an expected call of RunReadonlyTransaction.
func (mr *MockReadTransactionCoordinatorMockRecorder) RunReadonlyTransaction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReadonlyTransaction", reflect.TypeOf((*MockReadTransactionCoordinator)(nil).RunReadonlyTransaction), varargs...)
}

// MockReadwriteTransactionCoordinator is a mock of ReadwriteTransactionCoordinator interface.
type MockReadwriteTransactionCoordinator struct {
	ctrl     *gomock.Controller
	recorder *MockReadwriteTransactionCoordinatorMockRecorder
}

// MockReadwriteTransactionCoordinatorMockRecorder is the mock recorder for MockReadwriteTransactionCoordinator.
type MockReadwriteTransactionCoordinatorMockRecorder struct {
	mock *MockReadwriteTransactionCoordinator
}

// NewMockReadwriteTransactionCoordinator creates a new mock instance.
func NewMockReadwriteTransactionCoordinator(ctrl *gomock.Controller) *MockReadwriteTransactionCoordinator {
	mock := &MockReadwriteTransactionCoordinator{ctrl: ctrl}
	mock.recorder = &MockReadwriteTransactionCoordinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadwriteTransactionCoordinator) EXPECT() *MockReadwriteTransactionCoordinatorMockRecorder {
	return m.recorder
}

// RunReadwriteTransaction mocks base method.
func (m *MockReadwriteTransactionCoordinator) RunReadwriteTransaction(arg0 context.Context, arg1 func(context.Context, dal.ReadwriteTransaction) error, arg2 ...dal.TransactionOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunReadwriteTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunReadwriteTransaction indicates an expected call of RunReadwriteTransaction.
func (mr *MockReadwriteTransactionCoordinatorMockRecorder) RunReadwriteTransaction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReadwriteTransaction", reflect.TypeOf((*MockReadwriteTransactionCoordinator)(nil).RunReadwriteTransaction), varargs...)
}

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// Options mocks base method.
func (m *MockTransaction) Options() dal.TransactionOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Options")
	ret0, _ := ret[0].(dal.TransactionOptions)
	return ret0
}

// Options indicates an expected call of Options.
func (mr *MockTransactionMockRecorder) Options() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Options", reflect.TypeOf((*MockTransaction)(nil).Options))
}

// MockReadTransaction is a mock of ReadTransaction interface.
type MockReadTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockReadTransactionMockRecorder
}

// MockReadTransactionMockRecorder is the mock recorder for MockReadTransaction.
type MockReadTransactionMockRecorder struct {
	mock *MockReadTransaction
}

// NewMockReadTransaction creates a new mock instance.
func NewMockReadTransaction(ctrl *gomock.Controller) *MockReadTransaction {
	mock := &MockReadTransaction{ctrl: ctrl}
	mock.recorder = &MockReadTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadTransaction) EXPECT() *MockReadTransactionMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockReadTransaction) Get(arg0 context.Context, arg1 dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockReadTransactionMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockReadTransaction)(nil).Get), arg0, arg1)
}

// GetMulti mocks base method.
func (m *MockReadTransaction) GetMulti(arg0 context.Context, arg1 []dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockReadTransactionMockRecorder) GetMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockReadTransaction)(nil).GetMulti), arg0, arg1)
}

// Options mocks base method.
func (m *MockReadTransaction) Options() dal.TransactionOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Options")
	ret0, _ := ret[0].(dal.TransactionOptions)
	return ret0
}

// Options indicates an expected call of Options.
func (mr *MockReadTransactionMockRecorder) Options() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Options", reflect.TypeOf((*MockReadTransaction)(nil).Options))
}

// QueryAllRecords mocks base method.
func (m *MockReadTransaction) QueryAllRecords(arg0 context.Context, arg1 dal.Query) ([]dal.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAllRecords", arg0, arg1)
	ret0, _ := ret[0].([]dal.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryAllRecords indicates an expected call of QueryAllRecords.
func (mr *MockReadTransactionMockRecorder) QueryAllRecords(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAllRecords", reflect.TypeOf((*MockReadTransaction)(nil).QueryAllRecords), arg0, arg1)
}

// QueryReader mocks base method.
func (m *MockReadTransaction) QueryReader(arg0 context.Context, arg1 dal.Query) (dal.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryReader", arg0, arg1)
	ret0, _ := ret[0].(dal.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryReader indicates an expected call of QueryReader.
func (mr *MockReadTransactionMockRecorder) QueryReader(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryReader", reflect.TypeOf((*MockReadTransaction)(nil).QueryReader), arg0, arg1)
}

// MockReadwriteTransaction is a mock of ReadwriteTransaction interface.
type MockReadwriteTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockReadwriteTransactionMockRecorder
}

// MockReadwriteTransactionMockRecorder is the mock recorder for MockReadwriteTransaction.
type MockReadwriteTransactionMockRecorder struct {
	mock *MockReadwriteTransaction
}

// NewMockReadwriteTransaction creates a new mock instance.
func NewMockReadwriteTransaction(ctrl *gomock.Controller) *MockReadwriteTransaction {
	mock := &MockReadwriteTransaction{ctrl: ctrl}
	mock.recorder = &MockReadwriteTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadwriteTransaction) EXPECT() *MockReadwriteTransactionMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockReadwriteTransaction) Delete(arg0 context.Context, arg1 *dal.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReadwriteTransactionMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReadwriteTransaction)(nil).Delete), arg0, arg1)
}

// DeleteMulti mocks base method.
func (m *MockReadwriteTransaction) DeleteMulti(arg0 context.Context, arg1 []*dal.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMulti indicates an expected call of DeleteMulti.
func (mr *MockReadwriteTransactionMockRecorder) DeleteMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMulti", reflect.TypeOf((*MockReadwriteTransaction)(nil).DeleteMulti), arg0, arg1)
}

// Get mocks base method.
func (m *MockReadwriteTransaction) Get(arg0 context.Context, arg1 dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockReadwriteTransactionMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockReadwriteTransaction)(nil).Get), arg0, arg1)
}

// GetMulti mocks base method.
func (m *MockReadwriteTransaction) GetMulti(arg0 context.Context, arg1 []dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockReadwriteTransactionMockRecorder) GetMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockReadwriteTransaction)(nil).GetMulti), arg0, arg1)
}

// ID mocks base method.
func (m *MockReadwriteTransaction) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockReadwriteTransactionMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockReadwriteTransaction)(nil).ID))
}

// Insert mocks base method.
func (m *MockReadwriteTransaction) Insert(arg0 context.Context, arg1 dal.Record, arg2 ...dal.InsertOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockReadwriteTransactionMockRecorder) Insert(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockReadwriteTransaction)(nil).Insert), varargs...)
}

// Options mocks base method.
func (m *MockReadwriteTransaction) Options() dal.TransactionOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Options")
	ret0, _ := ret[0].(dal.TransactionOptions)
	return ret0
}

// Options indicates an expected call of Options.
func (mr *MockReadwriteTransactionMockRecorder) Options() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Options", reflect.TypeOf((*MockReadwriteTransaction)(nil).Options))
}

// QueryAllRecords mocks base method.
func (m *MockReadwriteTransaction) QueryAllRecords(arg0 context.Context, arg1 dal.Query) ([]dal.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAllRecords", arg0, arg1)
	ret0, _ := ret[0].([]dal.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryAllRecords indicates an expected call of QueryAllRecords.
func (mr *MockReadwriteTransactionMockRecorder) QueryAllRecords(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAllRecords", reflect.TypeOf((*MockReadwriteTransaction)(nil).QueryAllRecords), arg0, arg1)
}

// QueryReader mocks base method.
func (m *MockReadwriteTransaction) QueryReader(arg0 context.Context, arg1 dal.Query) (dal.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryReader", arg0, arg1)
	ret0, _ := ret[0].(dal.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryReader indicates an expected call of QueryReader.
func (mr *MockReadwriteTransactionMockRecorder) QueryReader(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryReader", reflect.TypeOf((*MockReadwriteTransaction)(nil).QueryReader), arg0, arg1)
}

// Set mocks base method.
func (m *MockReadwriteTransaction) Set(arg0 context.Context, arg1 dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockReadwriteTransactionMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockReadwriteTransaction)(nil).Set), arg0, arg1)
}

// SetMulti mocks base method.
func (m *MockReadwriteTransaction) SetMulti(arg0 context.Context, arg1 []dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMulti indicates an expected call of SetMulti.
func (mr *MockReadwriteTransactionMockRecorder) SetMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMulti", reflect.TypeOf((*MockReadwriteTransaction)(nil).SetMulti), arg0, arg1)
}

// Update mocks base method.
func (m *MockReadwriteTransaction) Update(arg0 context.Context, arg1 *dal.Key, arg2 []dal.Update, arg3 ...dal.Precondition) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReadwriteTransactionMockRecorder) Update(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReadwriteTransaction)(nil).Update), varargs...)
}

// UpdateMulti mocks base method.
func (m *MockReadwriteTransaction) UpdateMulti(arg0 context.Context, arg1 []*dal.Key, arg2 []dal.Update, arg3 ...dal.Precondition) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMulti", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMulti indicates an expected call of UpdateMulti.
func (mr *MockReadwriteTransactionMockRecorder) UpdateMulti(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMulti", reflect.TypeOf((*MockReadwriteTransaction)(nil).UpdateMulti), varargs...)
}

// MockReadSession is a mock of ReadSession interface.
type MockReadSession struct {
	ctrl     *gomock.Controller
	recorder *MockReadSessionMockRecorder
}

// MockReadSessionMockRecorder is the mock recorder for MockReadSession.
type MockReadSessionMockRecorder struct {
	mock *MockReadSession
}

// NewMockReadSession creates a new mock instance.
func NewMockReadSession(ctrl *gomock.Controller) *MockReadSession {
	mock := &MockReadSession{ctrl: ctrl}
	mock.recorder = &MockReadSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadSession) EXPECT() *MockReadSessionMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockReadSession) Get(arg0 context.Context, arg1 dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockReadSessionMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockReadSession)(nil).Get), arg0, arg1)
}

// GetMulti mocks base method.
func (m *MockReadSession) GetMulti(arg0 context.Context, arg1 []dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockReadSessionMockRecorder) GetMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockReadSession)(nil).GetMulti), arg0, arg1)
}

// QueryAllRecords mocks base method.
func (m *MockReadSession) QueryAllRecords(arg0 context.Context, arg1 dal.Query) ([]dal.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAllRecords", arg0, arg1)
	ret0, _ := ret[0].([]dal.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryAllRecords indicates an expected call of QueryAllRecords.
func (mr *MockReadSessionMockRecorder) QueryAllRecords(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAllRecords", reflect.TypeOf((*MockReadSession)(nil).QueryAllRecords), arg0, arg1)
}

// QueryReader mocks base method.
func (m *MockReadSession) QueryReader(arg0 context.Context, arg1 dal.Query) (dal.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryReader", arg0, arg1)
	ret0, _ := ret[0].(dal.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryReader indicates an expected call of QueryReader.
func (mr *MockReadSessionMockRecorder) QueryReader(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryReader", reflect.TypeOf((*MockReadSession)(nil).QueryReader), arg0, arg1)
}

// MockWriteSession is a mock of WriteSession interface.
type MockWriteSession struct {
	ctrl     *gomock.Controller
	recorder *MockWriteSessionMockRecorder
}

// MockWriteSessionMockRecorder is the mock recorder for MockWriteSession.
type MockWriteSessionMockRecorder struct {
	mock *MockWriteSession
}

// NewMockWriteSession creates a new mock instance.
func NewMockWriteSession(ctrl *gomock.Controller) *MockWriteSession {
	mock := &MockWriteSession{ctrl: ctrl}
	mock.recorder = &MockWriteSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriteSession) EXPECT() *MockWriteSessionMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockWriteSession) Delete(arg0 context.Context, arg1 *dal.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWriteSessionMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWriteSession)(nil).Delete), arg0, arg1)
}

// DeleteMulti mocks base method.
func (m *MockWriteSession) DeleteMulti(arg0 context.Context, arg1 []*dal.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMulti indicates an expected call of DeleteMulti.
func (mr *MockWriteSessionMockRecorder) DeleteMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMulti", reflect.TypeOf((*MockWriteSession)(nil).DeleteMulti), arg0, arg1)
}

// Insert mocks base method.
func (m *MockWriteSession) Insert(arg0 context.Context, arg1 dal.Record, arg2 ...dal.InsertOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockWriteSessionMockRecorder) Insert(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockWriteSession)(nil).Insert), varargs...)
}

// Set mocks base method.
func (m *MockWriteSession) Set(arg0 context.Context, arg1 dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockWriteSessionMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockWriteSession)(nil).Set), arg0, arg1)
}

// SetMulti mocks base method.
func (m *MockWriteSession) SetMulti(arg0 context.Context, arg1 []dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMulti indicates an expected call of SetMulti.
func (mr *MockWriteSessionMockRecorder) SetMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMulti", reflect.TypeOf((*MockWriteSession)(nil).SetMulti), arg0, arg1)
}

// Update mocks base method.
func (m *MockWriteSession) Update(arg0 context.Context, arg1 *dal.Key, arg2 []dal.Update, arg3 ...dal.Precondition) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWriteSessionMockRecorder) Update(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWriteSession)(nil).Update), varargs...)
}

// UpdateMulti mocks base method.
func (m *MockWriteSession) UpdateMulti(arg0 context.Context, arg1 []*dal.Key, arg2 []dal.Update, arg3 ...dal.Precondition) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMulti", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMulti indicates an expected call of UpdateMulti.
func (mr *MockWriteSessionMockRecorder) UpdateMulti(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMulti", reflect.TypeOf((*MockWriteSession)(nil).UpdateMulti), varargs...)
}

// MockReadwriteSession is a mock of ReadwriteSession interface.
type MockReadwriteSession struct {
	ctrl     *gomock.Controller
	recorder *MockReadwriteSessionMockRecorder
}

// MockReadwriteSessionMockRecorder is the mock recorder for MockReadwriteSession.
type MockReadwriteSessionMockRecorder struct {
	mock *MockReadwriteSession
}

// NewMockReadwriteSession creates a new mock instance.
func NewMockReadwriteSession(ctrl *gomock.Controller) *MockReadwriteSession {
	mock := &MockReadwriteSession{ctrl: ctrl}
	mock.recorder = &MockReadwriteSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadwriteSession) EXPECT() *MockReadwriteSessionMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockReadwriteSession) Delete(arg0 context.Context, arg1 *dal.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReadwriteSessionMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReadwriteSession)(nil).Delete), arg0, arg1)
}

// DeleteMulti mocks base method.
func (m *MockReadwriteSession) DeleteMulti(arg0 context.Context, arg1 []*dal.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMulti indicates an expected call of DeleteMulti.
func (mr *MockReadwriteSessionMockRecorder) DeleteMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMulti", reflect.TypeOf((*MockReadwriteSession)(nil).DeleteMulti), arg0, arg1)
}

// Get mocks base method.
func (m *MockReadwriteSession) Get(arg0 context.Context, arg1 dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockReadwriteSessionMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockReadwriteSession)(nil).Get), arg0, arg1)
}

// GetMulti mocks base method.
func (m *MockReadwriteSession) GetMulti(arg0 context.Context, arg1 []dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockReadwriteSessionMockRecorder) GetMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockReadwriteSession)(nil).GetMulti), arg0, arg1)
}

// Insert mocks base method.
func (m *MockReadwriteSession) Insert(arg0 context.Context, arg1 dal.Record, arg2 ...dal.InsertOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockReadwriteSessionMockRecorder) Insert(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockReadwriteSession)(nil).Insert), varargs...)
}

// QueryAllRecords mocks base method.
func (m *MockReadwriteSession) QueryAllRecords(arg0 context.Context, arg1 dal.Query) ([]dal.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAllRecords", arg0, arg1)
	ret0, _ := ret[0].([]dal.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryAllRecords indicates an expected call of QueryAllRecords.
func (mr *MockReadwriteSessionMockRecorder) QueryAllRecords(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAllRecords", reflect.TypeOf((*MockReadwriteSession)(nil).QueryAllRecords), arg0, arg1)
}

// QueryReader mocks base method.
func (m *MockReadwriteSession) QueryReader(arg0 context.Context, arg1 dal.Query) (dal.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryReader", arg0, arg1)
	ret0, _ := ret[0].(dal.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryReader indicates an expected call of QueryReader.
func (mr *MockReadwriteSessionMockRecorder) QueryReader(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryReader", reflect.TypeOf((*MockReadwriteSession)(nil).QueryReader), arg0, arg1)
}

// Set mocks base method.
func (m *MockReadwriteSession) Set(arg0 context.Context, arg1 dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockReadwriteSessionMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockReadwriteSession)(nil).Set), arg0, arg1)
}

// SetMulti mocks base method.
func (m *MockReadwriteSession) SetMulti(arg0 context.Context, arg1 []dal.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMulti", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMulti indicates an expected call of SetMulti.
func (mr *MockReadwriteSessionMockRecorder) SetMulti(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMulti", reflect.TypeOf((*MockReadwriteSession)(nil).SetMulti), arg0, arg1)
}

// Update mocks base method.
func (m *MockReadwriteSession) Update(arg0 context.Context, arg1 *dal.Key, arg2 []dal.Update, arg3 ...dal.Precondition) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReadwriteSessionMockRecorder) Update(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReadwriteSession)(nil).Update), varargs...)
}

// UpdateMulti mocks base method.
func (m *MockReadwriteSession) UpdateMulti(arg0 context.Context, arg1 []*dal.Key, arg2 []dal.Update, arg3 ...dal.Precondition) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMulti", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMulti indicates an expected call of UpdateMulti.
func (mr *MockReadwriteSessionMockRecorder) UpdateMulti(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMulti", reflect.TypeOf((*MockReadwriteSession)(nil).UpdateMulti), varargs...)
}
